<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Xem_img-responsive</name>
   <tag></tag>
   <elementGuidId>21214b20-d588-4eab-8ef0-363dcd9c6af4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='block-system-main']/div/div/div[2]/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.views-row.views-row-2.views-row-even > div.views-field.views-field-field-photo > div.field-content > a > img.img-responsive</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-responsive</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://nguoiyeudep.com/sites/default/files/styles/new_mem/public/user-photos/r_1575182139_62474311_1187729094740379_620256744274132992_n.jpg?itok=yW2Uwk-M</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>171</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>171</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-system-main&quot;)/div[@class=&quot;view view-frontpage-members view-id-frontpage_members view-display-id-page_1 block-members view-dom-id-0c7fbda1f7f74444be6442b63ce4f0ac jquery-once-2-processed&quot;]/div[@class=&quot;view-content&quot;]/div[@class=&quot;views-row views-row-2 views-row-even&quot;]/div[@class=&quot;views-field views-field-field-photo&quot;]/div[@class=&quot;field-content&quot;]/a[1]/img[@class=&quot;img-responsive&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='block-system-main']/div/div/div[2]/div/div/a/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://nguoiyeudep.com/sites/default/files/styles/new_mem/public/user-photos/r_1575182139_62474311_1187729094740379_620256744274132992_n.jpg?itok=yW2Uwk-M')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='block-system-main']/div/div/div[3]/div/div/a/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://nguoiyeudep.com/sites/default/files/styles/new_mem/public/user-photos/r_1599108889_96430354_1599101796933423_1888512380070002688_o_0.jpg?itok=ZWfDfygv')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/a/img</value>
   </webElementXpaths>
</WebElementEntity>
