<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Ti l Ngi NamNgi n   cn tm - Tt c -Ngi _a352c2</name>
   <tag></tag>
   <elementGuidId>bdb62e54-e886-451b-923b-ae7db392a3a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='views-exposed-form-frontpage-members-page-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#views-exposed-form-frontpage-members-page-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>action</name>
      <type>Main</type>
      <value>/thanh-vien</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>method</name>
      <type>Main</type>
      <value>get</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>views-exposed-form-frontpage-members-page-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept-charset</name>
      <type>Main</type>
      <value>UTF-8</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Tôi là Người NamNgười nữ   cần tìm - Tất cả -Người NamNgười nữ tới-Năm1819202122232425262728293031323334353637383940 tới Tuổi từ-Năm1819202122232425262728293031323334353637383940 Tuổi từĐể mời  Cùng đi chơi / đi ăn / cafe / xem phim Dự sinh nhật / dự tiệcThăm gia đình, ra mắt bố mẹĐi du lịch, chơi dã ngoại / picnicHướng dẫn viên địa phương  Tại TP - Tất cả -Hà NộiTp Hồ Chí MinhĐà NẵngHuếAn GiangBà RịaBà Rịa - Vũng TàuBắc GiangBắc KạnBạc LiêuBắc NinhBến TreBiên HòaBình DươngBình PhướcBình ThuậnBình ĐịnhBuôn Ma ThuộtCà MauCần ThơCao BằngCao LãnhGia LaiGia NghĩaHà GiangHạ LongHà NamHà TĩnhHải DươngHải PhòngHậu GiangHòa BìnhHưng YênKhánh HòaKiên GiangKon TumLai ChâuLâm ĐồngLạng SơnLào CaiLong AnLong XuyênMỹ ThoNam ĐịnhNghệ AnNha TrangNinh BìnhNinh ThuậnPhan Rang - Tháp ChàmPhan ThiếtPhủ LýPhú ThọPhú YênPleikuQuảng BìnhQuảng NamQuảng NgãiQuảng NinhQuảng TrịQuy NhơnRạch GiáSóc TrăngSơn LaTam KỳTân AnTây NinhThái BìnhThái NguyênThanh HóaThủ Dầu MộtThừa Thiên HuếTiền GiangTrà VinhTuy HòaTuyên QuangVị ThanhViệt TrìVinhVĩnh LongVĩnh PhúcVĩnh YênYên BáiĐà LạtĐắk LắkĐắk NôngĐiện BiênĐiện Biên PhủĐông HàĐồng HớiĐồng NaiĐồng Tháp Thực hiện</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;views-exposed-form-frontpage-members-page-1&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@id='views-exposed-form-frontpage-members-page-1']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='block-views-exp-frontpage-members-page-1']/form</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hẹn hò đi chơi'])[1]/following::form[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='về NYD 1'])[1]/following::form[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
   </webElementXpaths>
</WebElementEntity>
