<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_JPEG  JPG, PNG_fa fa-desktop</name>
   <tag></tag>
   <elementGuidId>682b67b4-bbb5-4f42-a70f-6875e24d5252</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='photo-canvas-wrapper']/div[2]/div/div[2]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-desktop</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-desktop</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;photo-canvas-wrapper&quot;)/div[@class=&quot;photo-canvas-wrapper row&quot;]/div[@class=&quot;photo-field-wrapper col-md-2 pull-left&quot;]/div[@class=&quot;buttons-wrapper&quot;]/a[@class=&quot;link-button&quot;]/i[@class=&quot;fa fa-desktop&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='photo-canvas-wrapper']/div[2]/div/div[2]/a/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/a/i</value>
   </webElementXpaths>
</WebElementEntity>
